src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from plandiet_app.views import Index, MacroCalculatorView

urlpatterns = [
    path("", include("categories.urls")),
    path("", include("diets.urls")),
    path("", include("exercises.urls")),
    path("", include("plans.urls")),
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("macro_calculator/", MacroCalculatorView.as_view(), name="macro-calc"),
]

urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]
urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/exercises/urls.py
from django.urls import path

from exercises.views.exercise import (
    ExerciseCreateView,
    ExerciseDeleteView,
    ExerciseDetailView,
    ExerciseListView,
    ExerciseUpdateView,
)
from exercises.views.muscle_group import (
    MuscleGroupCreateView,
    MuscleGroupDeleteView,
    MuscleGroupListView,
    MuscleGroupUpdateView,
)
from exercises.views.sport_type import (
    SportTypeCreateView,
    SportTypeDeleteView,
    SportTypeListView,
    SportTypeUpdateView,
)

app_name = "exercises"


urlpatterns = [
    path("exercise/<int:pk>/", ExerciseDetailView.as_view(), name="exercise-detail"),
    path("exercises/", ExerciseListView.as_view(), name="exercises"),
    path("exercise/create/", ExerciseCreateView.as_view(), name="exercise-create"),
    path("exercise/<int:pk>/update/", ExerciseUpdateView.as_view(), name="exercise-update"),
    path("exercise/<int:pk>/delete/", ExerciseDeleteView.as_view(), name="exercise-delete"),
    path("sporttypes/", SportTypeListView.as_view(), name="sport-types"),
    path("sport-types/create/", SportTypeCreateView.as_view(), name="sport-type-create"),
    path("sport-types/<int:pk>/update/", SportTypeUpdateView.as_view(), name="sport-type-update"),
    path("sport-types/<int:pk>/delete/", SportTypeDeleteView.as_view(), name="sport-type-delete"),
    path("muscle-groups/", MuscleGroupListView.as_view(), name="muscle-groups"),
    path("muscle-groups/create/", MuscleGroupCreateView.as_view(), name="muscle-group-create"),
    path("muscle-groups/<int:pk>/update/", MuscleGroupUpdateView.as_view(), name="muscle-group-update"),
    path("muscle-groups/<int:pk>/delete/", MuscleGroupDeleteView.as_view(), name="muscle-group-delete"),
]

src/exercises/models.py
from django.db import models

from categories.models import Category
from exercises.choices import DIFFICULTIES


class MuscleGroup(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class SportType(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Exercise(models.Model):
    name = models.CharField(max_length=124)
    description = models.TextField()
    difficulty = models.CharField(choices=DIFFICULTIES, max_length=60)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, default=None)
    muscles = models.ManyToManyField(MuscleGroup)
    type = models.ManyToManyField(SportType)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["pk"]

src/exercises/views/exercise.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from exercises.models import Exercise


class ExerciseDetailView(DetailView):
    model = Exercise
    template_name = "exercises/exercise_detail.html"
    context_object_name = "exercise"


class ExerciseListView(ListView):
    model = Exercise
    template_name = "exercises/exercise_list.html"
    context_object_name = "exercises"
    paginate_by = 18


class ExerciseCreateView(CreateView):
    model = Exercise
    fields = "__all__"
    template_name = "exercises/exercise_form.html"
    success_url = reverse_lazy("exercises:exercises")


class ExerciseUpdateView(UpdateView):
    model = Exercise
    fields = "__all__"
    template_name = "exercises/exercise_form.html"
    success_url = reverse_lazy("exercises:exercises")


class ExerciseDeleteView(DeleteView):
    model = Exercise
    template_name = "exercises/exercise_confirm_delete.html"
    success_url = reverse_lazy("exercises:exercises")

src/exercises/views/muscle_group.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from exercises.models import MuscleGroup


class MuscleGroupListView(ListView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_list.html"
    context_object_name = "muscle_groups"


class MuscleGroupCreateView(CreateView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:muscle-groups")


class MuscleGroupUpdateView(UpdateView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:muscle-groups")


class MuscleGroupDeleteView(DeleteView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_confirm_delete.html"
    success_url = reverse_lazy("exercises:muscle-groups")

src/exercises/views/sport_type.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from exercises.models import SportType


class SportTypeListView(ListView):
    model = SportType
    template_name = "types/sport_type_list.html"
    context_object_name = "sport_types"


class SportTypeCreateView(CreateView):
    model = SportType
    template_name = "types/sport_type_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:sport-types")


class SportTypeUpdateView(UpdateView):
    model = SportType
    template_name = "types/sport_type_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:sport-types")


class SportTypeDeleteView(DeleteView):
    model = SportType
    template_name = "types/sport_type_confirm_delete.html"
    success_url = reverse_lazy("exercises:sport-types")

src/exercises/templates/exercises/exercise.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ exercise.name }}</h2>
    <ul>
        <li>Description: {{ exercise.description }}</li>
        <li>Difficulty: {{ exercise.difficulty }}</li>
        <li>Category:
            {% if exercise.category_id == 1 %}
                Endurance
            {% endif %}

            {% if exercise.category_id == 2 %}
                Strength
            {% endif %}

            {% if exercise.category_id == 3 %}
                Flexibility
            {% endif %}

            {% if exercise.category_id == 4 %}
                Balance
                {% endif %}
        </li>
        <li>Muscle parts involved:
            <ul>
                {% for muscle in exercise.muscles.all %}
                    <li>{{ muscle.name }}</li>
                {% endfor %}
            </ul>
        </li>
        <li>Type name:
            <ul>
                {% for sport in exercise.type.all %}
                    <li>{{ sport.name }}</li>
                {% endfor %}
            </ul>
        </li>
    </ul>
{% endblock %}

src/exercises/templates/exercises/exercise_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Delete Exercise</h2>
    <p>Are you sure you want to delete "{{ exercise.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'exercise-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

src/exercises/templates/exercises/exercise_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ exercise.name }}</h2>
    <ul>
        <li>Description: {{ exercise.description }}</li>
        <li>Difficulty: {{ exercise.difficulty }}</li>
        <li>Category: {{ exercise.category }}</li>
        <li>Muscle parts involved:
            <ul>
                {% for muscle in exercise.muscles.all %}
                    <li>{{ muscle.name }}</li>
                {% endfor %}
            </ul>
        </li>
        <li>Used in Sport Types such as:
            <ul>
                {% for sport in exercise.type.all %}
                    <li>{{ sport.name }}</li>
                {% endfor %}
            </ul>
        </li>
    </ul>
{% endblock %}

src/exercises/templates/exercises/exercise_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Exercise</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

src/exercises/templates/exercises/exercise_list.html
{% extends 'base.html' %}
{% block title %}
    Exercise list
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Exercises</h1>
            <a href="{% url 'exercises:exercise-create' %}" class="btn btn-primary">Add new Exercise</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Difficulty</th>
                    <th>Category</th>
                    <th>Muscles</th>
                    <th>Sport Types</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for exercise in exercises %}
                    <tr>
                        <td>{{ exercise.name }}</td>
                        <td>{{ exercise.description|truncatechars:20 }}</td>
                        <td>{{ exercise.difficulty }}</td>
                        <td>{{ exercise.category }}</td>
                        <td>
                            {% for muscle in exercise.muscles.all %}
                                {{ muscle.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}</td>
                        <td>
                            {% for sport_type in exercise.type.all %}
                                {{ sport_type.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}</td>
                        <td>
                            <a href="{% url 'exercises:exercise-detail' exercise.pk %}" class="btn btn-info">Details</a>
                            <a href="{% url 'exercises:exercise-update' exercise.pk %}" class="btn btn-dark">Update</a>
                            <a href="{% url 'exercises:exercise-delete' exercise.pk %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}