src/categories/urls.py
from django.urls import path

from categories import views

app_name = "categories"


urlpatterns = [
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path("categories/<int:pk>/", views.CategoryDetailView.as_view(), name="category-detail"),
    path("categories/delete/<int:pk>/", views.CategoryDeleteView.as_view(), name="category-delete"),
    path("categories/create/", views.CategoryCreateView.as_view(), name="category-create"),
    path("categories/update/<int:pk>", views.CategoryUpdateView.as_view(), name="category-update"),
]

src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from plandiet_app.views import Index, MacroCalculatorView

urlpatterns = [
    path("", include("categories.urls")),
    path("", include("diets.urls")),
    path("", include("exercises.urls")),
    path("", include("plans.urls")),
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("macro_calculator/", MacroCalculatorView.as_view(), name="macro-calc"),
]

urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]
urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/categories/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=60)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name

src/categories/forms.py
from django import forms

from .models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "description"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
        }

src/categories/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from categories.forms import CategoryForm
from categories.models import Category


class CategoryListView(ListView):
    model = Category
    template_name = "categories/category_list.html"
    context_object_name = "categories"


class CategoryDetailView(DetailView):
    model = Category
    template_name = "categories/category_detail.html"
    context_object_name = "category"


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "categories/category_create.html"
    success_url = reverse_lazy("categories:categories")


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = "categories/category_update.html"
    success_url = reverse_lazy("categories:categories")
    context_object_name = "category"


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = "categories/category_confirm_delete.html"
    success_url = reverse_lazy("categories:categories")
    context_object_name = "category"

src/categories/templates/categories/category.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2>{{ category.name }}</h2>
                <p>{{ category.description }}</p>
            </div>
        </div>
    </div>
{% endblock %}

src/categories/templates/categories/category_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
        <h1>Delete Category</h1>
        <p>Are you sure you want to delete "{{ category.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'categories:categories' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

src/categories/templates/categories/category_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
</div>

{% endblock %}

src/categories/templates/categories/category_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2>{{ category.name }}</h2>
                <p>{{ category.description }}</p>
            </div>
        </div>
    <a href="{% url 'categories:categories' %}" class="btn btn-success">Back</a>
    </div>
{% endblock %}

src/categories/templates/categories/category_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Categories</h1>
            <a href="{% url 'categories:category-create' %}" class="btn btn-primary">Add new Category</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                    <tr>
                        <td>{{ category.name }}</td>
                        <td>{{ category.description }}</td>
                        <td>
                            <a href="{% url 'categories:category-detail' category.pk %}" class="btn btn-info">Details</a>
                            <a href="{% url 'categories:category-update' category.pk %}" class="btn btn-dark">Update</a>
                            <a href="{% url 'categories:category-delete' category.pk %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/categories/templates/categories/category_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <h2>Update Category</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock %}