src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from plandiet_app.views import Index, MacroCalculatorView

urlpatterns = [
    path("", include("categories.urls")),
    path("", include("diets.urls")),
    path("", include("exercises.urls")),
    path("", include("plans.urls")),
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("macro_calculator/", MacroCalculatorView.as_view(), name="macro-calc"),
]

urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]
urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/exercises/urls.py
from django.urls import path

from exercises.views.exercise import (
    ExerciseCreateView,
    ExerciseDeleteView,
    ExerciseDetailView,
    ExerciseListView,
    ExerciseUpdateView,
)
from exercises.views.muscle_group import (
    MuscleGroupCreateView,
    MuscleGroupDeleteView,
    MuscleGroupListView,
    MuscleGroupUpdateView,
)
from exercises.views.sport_type import (
    SportTypeCreateView,
    SportTypeDeleteView,
    SportTypeListView,
    SportTypeUpdateView,
)

app_name = "exercises"


urlpatterns = [
    path("exercise/<int:pk>/", ExerciseDetailView.as_view(), name="exercise-detail"),
    path("exercises/", ExerciseListView.as_view(), name="exercises"),
    path("exercise/create/", ExerciseCreateView.as_view(), name="exercise-create"),
    path("exercise/<int:pk>/update/", ExerciseUpdateView.as_view(), name="exercise-update"),
    path("exercise/<int:pk>/delete/", ExerciseDeleteView.as_view(), name="exercise-delete"),
    path("sporttypes/", SportTypeListView.as_view(), name="sport-types"),
    path("sport-types/create/", SportTypeCreateView.as_view(), name="sport-type-create"),
    path("sport-types/<int:pk>/update/", SportTypeUpdateView.as_view(), name="sport-type-update"),
    path("sport-types/<int:pk>/delete/", SportTypeDeleteView.as_view(), name="sport-type-delete"),
    path("muscle-groups/", MuscleGroupListView.as_view(), name="muscle-groups"),
    path("muscle-groups/create/", MuscleGroupCreateView.as_view(), name="muscle-group-create"),
    path("muscle-groups/<int:pk>/update/", MuscleGroupUpdateView.as_view(), name="muscle-group-update"),
    path("muscle-groups/<int:pk>/delete/", MuscleGroupDeleteView.as_view(), name="muscle-group-delete"),
]

src/exercises/models.py
from django.db import models

from categories.models import Category
from exercises.choices import DIFFICULTIES


class MuscleGroup(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class SportType(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Exercise(models.Model):
    name = models.CharField(max_length=124)
    description = models.TextField()
    difficulty = models.CharField(choices=DIFFICULTIES, max_length=60)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, default=None)
    muscles = models.ManyToManyField(MuscleGroup)
    type = models.ManyToManyField(SportType)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["pk"]

src/exercises/views/exercise.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from exercises.models import Exercise


class ExerciseDetailView(DetailView):
    model = Exercise
    template_name = "exercises/exercise_detail.html"
    context_object_name = "exercise"


class ExerciseListView(ListView):
    model = Exercise
    template_name = "exercises/exercise_list.html"
    context_object_name = "exercises"
    paginate_by = 18


class ExerciseCreateView(CreateView):
    model = Exercise
    fields = "__all__"
    template_name = "exercises/exercise_form.html"
    success_url = reverse_lazy("exercises:exercises")


class ExerciseUpdateView(UpdateView):
    model = Exercise
    fields = "__all__"
    template_name = "exercises/exercise_form.html"
    success_url = reverse_lazy("exercises:exercises")


class ExerciseDeleteView(DeleteView):
    model = Exercise
    template_name = "exercises/exercise_confirm_delete.html"
    success_url = reverse_lazy("exercises:exercises")

src/exercises/views/muscle_group.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from exercises.models import MuscleGroup


class MuscleGroupListView(ListView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_list.html"
    context_object_name = "muscle_groups"


class MuscleGroupCreateView(CreateView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:muscle-groups")


class MuscleGroupUpdateView(UpdateView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:muscle-groups")


class MuscleGroupDeleteView(DeleteView):
    model = MuscleGroup
    template_name = "muscles/muscle_group_confirm_delete.html"
    success_url = reverse_lazy("exercises:muscle-groups")

src/exercises/views/sport_type.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from exercises.models import SportType


class SportTypeListView(ListView):
    model = SportType
    template_name = "types/sport_type_list.html"
    context_object_name = "sport_types"


class SportTypeCreateView(CreateView):
    model = SportType
    template_name = "types/sport_type_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:sport-types")


class SportTypeUpdateView(UpdateView):
    model = SportType
    template_name = "types/sport_type_form.html"
    fields = ["name"]
    success_url = reverse_lazy("exercises:sport-types")


class SportTypeDeleteView(DeleteView):
    model = SportType
    template_name = "types/sport_type_confirm_delete.html"
    success_url = reverse_lazy("exercises:sport-types")

src/exercises/templates/types/sport_type_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Confirm Deletion</h1>
    <p>Are you sure you want to delete "{{ sport_type.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm</button>
    </form>
{% endblock %}

src/exercises/templates/types/sport_type_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ sport_type.name }}</h1>
{% endblock %}

src/exercises/templates/types/sport_type_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Sport Type</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

src/exercises/templates/types/sport_type_list.html
{% extends 'base.html' %}
{% block title %}
    Sport Types list
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Sport Types</h1>
            <a href="{% url 'exercises:sport-type-create' %}" class="btn btn-primary">Add new Sport Type</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for sport_type in sport_types %}
                    <tr>
                        <td>{{ sport_type.name }}</td>
                        <td>
                            <a href="{% url 'exercises:sport-type-update' sport_type.pk %}" class="btn btn-dark">Update</a>
                            <a href="{% url 'exercises:sport-type-delete' sport_type.pk %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/exercises/templates/types/sporttype_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Confirm Deletion</h1>
    <p>Are you sure you want to delete "{{ sporttype.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm</button>
    </form>
{% endblock %}

src/exercises/templates/types/sporttype_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ sporttype.name }}</h1>
{% endblock %}

src/exercises/templates/types/sporttype_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Sport Type</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

src/exercises/templates/types/sporttype_list.html
{% extends 'base.html' %}
{% block title %}
    Sport Types list
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Sport Types</h1>
            <a href="{% url 'exercises:sporttype-create' %}" class="btn btn-primary">Add new Sport Type</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for sporttype in sporttypes %}
                    <tr>
                        <td>{{ sporttype.name }}</td>
                        <td>
                            <a href="{% url 'exercises:sporttype-update' sporttype.pk %}" class="btn btn-dark">Update</a>
                            <a href="{% url 'exercises:sporttype-delete' sporttype.pk %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}