src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from plandiet_app.views import Index, MacroCalculatorView

urlpatterns = [
    path("", include("categories.urls")),
    path("", include("diets.urls")),
    path("", include("exercises.urls")),
    path("", include("plans.urls")),
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("macro_calculator/", MacroCalculatorView.as_view(), name="macro-calc"),
]

urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]
urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/diets/urls.py
from django.urls import path

from diets import views

app_name = "diets"


urlpatterns = [
    path("diets/", views.DietListView.as_view(), name="diets"),
    path("diets/<int:pk>/", views.DietDetailView.as_view(), name="diet-detail"),
    path("diets/create/", views.DietCreateView.as_view(), name="diet-create"),
    path("diets/update/<int:pk>/", views.DietUpdateView.as_view(), name="diet-update"),
    path("diets/delete/<int:pk>/", views.DietDeleteView.as_view(), name="diet-delete"),
]

src/diets/models.py
from django.db import models
from django.urls import reverse


class Diet(models.Model):
    name = models.CharField(max_length=124)
    caloric_demand = models.IntegerField()
    carbs_demand = models.IntegerField()
    protein_demand = models.IntegerField()
    fat_demand = models.IntegerField()
    description = models.TextField()

    def get_absolute_url(self):
        return reverse("diets:diet-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["pk"]

src/diets/forms.py
from django import forms

from diets.models import Diet


class DietModelForm(forms.ModelForm):
    class Meta:
        model = Diet
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "caloric_demand": forms.NumberInput(attrs={"class": "form-control"}),
            "carbs_demand": forms.NumberInput(attrs={"class": "form-control"}),
            "protein_demand": forms.NumberInput(attrs={"class": "form-control"}),
            "fat_demand": forms.NumberInput(attrs={"class": "form-control"}),
            "description": forms.TextInput(attrs={"class": "form-control"}),
        }

src/diets/views.py
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from diets.forms import DietModelForm
from diets.models import Diet


class DietListView(ListView):
    model = Diet
    template_name = "diets/diet_list.html"
    context_object_name = "diets"
    paginate_by = 10


class DietDetailView(DetailView):
    model = Diet
    template_name = "diets/diet_detail.html"
    context_object_name = "diet"


class DietCreateView(CreateView):
    form_class = DietModelForm
    template_name = "diets/diet_create.html"

    def get_success_url(self):
        return reverse("diets:diet-detail", kwargs={"pk": self.object.pk})


class DietUpdateView(UpdateView):
    model = Diet
    form_class = DietModelForm
    template_name = "diets/diet_update.html"


class DietDeleteView(DeleteView):
    model = Diet
    template_name = "diets/diet_delete.html"
    success_url = "/diets/"

src/diets/templates/diets/diet.html
{% extends 'base.html' %}
{% block title %}
    Diet no.{{ diet.id }}
{% endblock %}
{% block content %}
    <div class="diet-box">
    <h2 class="p-lower">Diet {{ diet.name }}</h2>
    <p>{{ diet.description }}</p>
    <ul>
        <li>Calories: {{ diet.caloric_demand }} kcal</li>
        <li>Carbs: {{ diet.carbs_demand }} g</li>
        <li>Proteins: {{ diet.protein_demand }} g</li>
        <li>Fats: {{ diet.fat_demand }} g</li>
    </ul>
    <a class="btn btn-outline-dark" href="{% url 'diets:diet-list' %}">To diets list</a>
    </div>
{% endblock %}

src/diets/templates/diets/diet_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Add
{% endblock %}
{% block content %}

    <form method="post" class="form-signin" style="margin-top: 50px">
    <h2>Add diet</h2>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="add" class="widthe btn btn-warning btn-lg">
    </form>

{% endblock %}

src/diets/templates/diets/diet_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Delete
{% endblock %}
{% block content %}
    <h2>Delete {{ object.name }}</h2>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <h1>Do you want to delete the diet '{{ object.name }}'?</h1>
        <p><input class="btn btn-info" type="submit" value="Yes"> <a class="btn btn-warning" href="{% url 'diets:diet-list' %}">Cancel</a></p>
    </form>

{% endblock %}

src/diets/templates/diets/diet_detail.html
{% extends 'base.html' %}
{% block title %}
    Diet no.{{ diet.id }}
{% endblock %}
{% block content %}
    <div class="diet-box">
    <h2 class="p-lower">Diet {{ diet.name }}</h2>
    <p>{{ diet.description }}</p>
    <ul>
        <li>Calories: {{ diet.caloric_demand }} kcal</li>
        <li>Carbs: {{ diet.carbs_demand }} g</li>
        <li>Proteins: {{ diet.protein_demand }} g</li>
        <li>Fats: {{ diet.fat_demand }} g</li>
    </ul>
    <a class="btn btn-outline-dark" href="{% url 'diets:diets' %}">To diets list</a>
    </div>
{% endblock %}

src/diets/templates/diets/diet_list.html
{% extends 'base.html' %}
{% block title %}
    Diets list
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Diets</h1>
            <a href="{% url 'diets:diet-create' %}" class="btn btn-primary">Add new Diet</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for diet in diets %}
                    <tr>
                        <td>{{ diet.name }}</td>
                        <td>{{ diet.description }}</td>
                        <td>
                            <a href="{% url 'diets:diet-detail' diet.pk %}" class="btn btn-info">Details</a>
                            <a href="{% url 'diets:diet-update' diet.pk %}" class="btn btn-dark">Update</a>
                            <a href="{% url 'diets:diet-delete' diet.pk %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/diets/templates/diets/diet_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update
{% endblock %}
{% block content %}


    <form method="post" class="form-signin" style="margin-top: 50px">
    <h2>Update diet '{{ object.name }}'</h2>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="save" class="widthe btn btn-danger btn-lg">
    </form>

{% endblock %}